fix(cli): doomscript: end-of-file error
534b6403508136e6667a26b43c12c63f053f9b35 introduced the same regression
previously introduced in bac90c0: it adds a quoted argument including
whitespace to `$emacs`, but the contents of that variable are not
evaluated by the shell. This means the quotes do not prevent word
splitting and are not removed, resulting in Emacs getting invoked with
separate arguments like `"(setq` and `warning-inhibit-types`:

```
$ bin/doomscript /tmp/doomscript

Error: end-of-file nil
  command-line-1(("--eval" "\"(setq" "warning-inhibit-types" "'((files" "missing-lexbind-cookie)))\"" "--load" "/home/marienz/src/doomemacs/early-init" "--load"
 "/tmp/doomscript" "--"))
  command-line()
  normal-top-level()
End of file during parsing
```

If we were using Bash we could fix this by using an array, but in
portable shell our options are more limited.

Fortunately, `$emacs` is only used twice, and one of them does not need
most of the arguments we are adding because it adds `-Q` and does not
load Doom. So fix it by replacing that one with `$EMACS --batch` and
inlining the rest of `$emacs` into its only remaining user.

Amend: 534b6403508136e6667a26b43c12c63f053f9b35